### ISSUE TITLE
Upgrade from 5.4.0 to 5.5 errors

### ISSUE THREAD

**Issue by sfc-gh-kleonhard** [bazelbuild/rules_java#103]
Did something change in between these versions requiring other changes?

```
ERROR: .../external/bazel_tools/src/tools/launcher/BUILD:9:14: While resolving toolchains for target @bazel_tools//src/tools/launcher:launcher: invalid registered toolchain '@remotejdk19_macos_aarch64_toolchain_config_repo//:toolchain': no such package '@remotejdk19_macos_aarch64_toolchain_config_repo//': The repository '@remotejdk19_macos_aarch64_toolchain_config_repo' could not be resolved: Repository '@remotejdk19_macos_aarch64_toolchain_config_repo' is not defined
```

**Comment by fabianhjr** [comment]
Have the same issue on a Nix Flakes + Bazel repo.

**Comment by anthonyjpratti** [comment]
This should be fixed by #106. In the meantime, you can resolve this by including `remote_jdk19_repos()` below `rules_java_dependencies` in your `WORKSPACE` file.

**Comment by sfc-gh-kleonhard** [comment]
Thanks for the fast turnaround. Once the change is released, I'll give it a shot. Any guess as to when the next release will be?

**Comment by anthonyjpratti** [comment]
> Thanks for the fast turnaround. Once the change is released, I'll give it a shot. Any guess as to when the next release will be?

No idea! I'm not a maintainer of rules_java, just happened to hit this issue at the same time.
