### ISSUE TITLE
Dependency on `rules_license`

### ISSUE THREAD

**Issue by ylecornec** [bazelbuild/rules_java#105]
A dependency on `rules_license` may be missing from rules_java's `MODULE.bazel` file.

The problem is that the `external/rules_java~5.5.0~toolchains~remote_java_tools/java_tools/zlib/BUILD.bazel` file contains a `load("@rules_license//rules:license.bzl", "license")` statement which can provoque the following error.

## Repro
The following command:
```
bazel build @@rules_java~5.5.0~toolchains~remote_java_tools//java_tools/zlib --enable_bzlmod
```
fails with:
```
No repository visible as '@rules_license' from repository '@rules_java~5.5.0~toolchains~remote_java_tools'
```

with an empty `WORKSPACE` file and the following `MODULE.bazel` file:
```
# MODULE.bazel
module(
    name = "repro",
    version = "0.1",
)

bazel_dep(name = "rules_java", version = "5.5.0")
```
and `bazel version` = `6.1.2`.

**Comment by aaronmondal** [comment]
I just hit this as well. Looks like a bug.

- https://github.com/bazelbuild/stardoc/issues/156
