### ISSUE TITLE
rules_java > 7.2.0 incorrectly states it is compatible with Bazel >= 6.4.0

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/rules_java#159]
The `bazel_compatibility` attribute in MODULE.bazel contains `>=6.4.0`, but it is actually not compatible with 6.4.0. The last version that is compatible with 6.4.0 is rules_java@7.2.0.

See https://github.com/bazelbuild/rules_java/pull/151#issuecomment-1837071649

**Comment by hvadehra** [comment]
Fixed from v7.3.2 onwards
