### ISSUE TITLE
Release: rules_java 7.3.2

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_java#163]
As part of https://github.com/bazelbuild/bazel/issues/14127, I need to update Bazel to a version of rules_java that includes d43c5d07b1756ea0954f6b7af47ac3f2f76e1d1b.

Can we cut a new rules_java 7.3.2 at head and then update Bazel to use it (I can make that update if that's easier).

cc @bazelbuild/triage

**Comment by katre** [comment]
Looks like 069da660b29f3ea0dd1ce3aac795f9fbbff4d86c bumped the version number.

**Comment by hvadehra** [comment]
Yes, pushing a release now.

**Comment by hvadehra** [comment]
Released: https://github.com/bazelbuild/rules_java/releases/tag/7.3.2

We can update this in Bazel once https://github.com/bazelbuild/bazel-central-registry/pull/1226 is merged.

**Comment by hvadehra** [comment]
Added to BCR.
