### ISSUE TITLE
Release: rules_java 7.4.0 on BCR

### ISSUE THREAD

**Issue by vorburger** [bazelbuild/rules_java#169]
I would like to use [the rules_java 7.4.0 release](https://github.com/bazelbuild/rules_java/releases/tag/7.4.0) from yesterday,

in order [to remove an ugly workaround](https://github.com/enola-dev/enola/pull/452) (`--nojava_header_compilation`) in my project (see https://github.com/bazelbuild/bazel/issues/21119),

but it looks like that v7.4.0 hasn't quite made it to BCR just yet? As of writing this I am getting this error:

    ERROR: Error computing the main repository mapping: in module dependency chain <root> -> rules_java@7.4.0: module not found in registries: rules_java@7.4.0

and indeed it's not on https://registry.bazel.build/modules/rules_java, yet.

Would it be possible to do the needful to have it appear there some time? Thanks!

cc @bazelbuild/triage

**Comment by fmeum** [comment]
You can track https://github.com/bazelbuild/bazel-central-registry/pull/1453. It needs a few fixes to metadata.

**Comment by vorburger** [comment]
@keertk @fmeum it works great, thank you! (See https://github.com/enola-dev/enola/pull/452.)
