### ISSUE TITLE
Add support for JDK 22

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_java#180]
JDK 22 release is available since 19th March 2024.

**Comment by hvadehra** [comment]
While we have added STS java releases in the past, we've also been dropping them, keeping only the LTS ones around. This probably ends up creating too much churn, and unnecessary breakage on updating `rules_java`.

I think it's somewhat trivial for users of `rules_java` to declare the repository(ies) themselves using `remote_java_repository`. 

@davido Is there any added benefit to the declarations living in `rules_java`?
