### ISSUE TITLE
Release: rules_java 7.6.0

### ISSUE THREAD

**Issue by hvadehra** [bazelbuild/rules_java#186]
Opening this to track the next `rules_java` release (with a new `java_tools` release). Before starting the process, I'd to like to:

1. Try re-enabling the execution Bazel's tests before making the release. Failing that, at least run them manually, so unblock the other steps here.
2. Figure out if we should bump the major version. 
    - are there any _potentially_ breaking changes?
    - do any/all the changes at HEAD need to be cherry-picked into Bazel 7.x?
    - maybe we always move to the next major version after Bazel X is cut, following a parallel release management process?

I'm going to work through these over the next few days.

**Comment by hvadehra** [comment]
Changes since the last release:

| commit | author | desc | 
| --- | --- | --- |
| 915944e | fmeum | Register Java 8 runtimes with Bzlmod |
| 000ef3c  | comius | Stop returning legacy struct providers from java_toolchain_alias |
| f195f33 | fmeum | Add JDK 8 `tools.jar` contents to bootclasspath |
| 355d6b0 |  hvadehra | Propagate all bzl deps for tests |
| 6f3e7a8 | hvadehra | LSC(tp): Add `load()` statements for the builtin top-level java symbols |
| d413f31 | hvadehra | LSC: Add `load()` statements for the builtin java rules |
| 1a8f8c6 | hvadehra | LSC(tp): Add `load()` statements for the builtin top-level java symbols |
| 69dd554 | srdio-humio | #Make jmods available from the jdk BUILD file |

Nothing looks like it should require a major version bump. 

@fmeum @srdo-humio Is there a strong desire to get your changes in Bazel 7.2.0? If so, I think we will need to make this release by Monday.

**Comment by fmeum** [comment]
@hvadehra My changes to rules_java itself aren't that important, but the java_tools update would include relevant Turbine fixes for Java 21 language features and, ideally, also https://github.com/bazelbuild/bazel/pull/22197.

**Comment by hvadehra** [comment]
Ack, I'm planning to get started on the `java_tools` release now. I'm not sure we can get https://github.com/bazelbuild/bazel/pull/22197 in before Monday. @cushon  is currently OOO and I believe there are still some unresolved concerns around the licensing of Oracle graalvm.

**Comment by srdo-humio** [comment]
@hvadehra The jmods change is easy to work around locally, but getting an upgrade of Turbine into 7.2.0 would be nice for https://github.com/google/turbine/commit/ff491a51ef28f3398a3a5d4b4b7ae78965562a51, to allow targeting Java 21 with `--release`.
