### ISSUE TITLE
rules_java_toolchains macro broken in 7.6.2

### ISSUE THREAD

**Issue by tmhdgsn** [bazelbuild/rules_java#192]
The 7.6.2 release has a breaking change to the rules_java_toolchains macro in //java/repositories.bzl

Looks like it's just missing the call to .items() and then to iterate through the resulting item list

**Comment by fmeum** [comment]
@hvadehra

**Comment by hvadehra** [comment]
Yikes. Fix incoming.

**Comment by hvadehra** [comment]
v7.6.3 is out now with the fix. Let me know if things are resolved with it.
