### ISSUE TITLE
Bug: Cycle in the workspace file detected

### ISSUE THREAD

**Issue by daniel-b2c2** [bazelbuild/rules_java#225]
As reported here:

https://github.com/bazel-contrib/bazel_features/issues/70#issue-2538854653

> ```
> Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
> The following chain of repository dependencies lead to the missing definition.
>  - @@bazel_features
> This could either mean you have to add the '@@bazel_features' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
> Computing main repo mapping:
> ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
> ```

I'm not an expert, just somebody who wants to see this fixed after having to upgrade:

Overheard:
> I'm pretty sure that the bug is in the transitively updated rules_java, which is used by Bazel's workspace suffix but doesn't properly declare the dep on bazel_features here: https://github.com/bazelbuild/rules_java/blob/master/java/repositories.bzl

Please advise if the issue above is caused by rules_java, or if the problem sits elsewhere

**Comment by fmeum** [comment]
I looked into this in detail now and can report that the full cycle is:
```
[Key{repoName=@@, rootModuleShouldSeeWorkspaceRepos=true}, external, com.google.devtools.build.lib.skyframe.ExternalPackageFunction$$Lambda/0x000000700120e428@cee2c26] -> [[/Users/fmeum/git/hirschgarten]/[WORKSPACE], 4, KeyForWorkspace{label=@@rules_sonatype//:defs.bzl, isBuildPrelude=false}, KeyForWorkspace{label=@@rules_sonatype//private/rules:sonatype_java_export.bzl, isBuildPrelude=false}, KeyForWorkspace{label=@@rules_jvm_external~//:defs.bzl, isBuildPrelude=false}, KeyForWorkspace{label=@@rules_jvm_external~//private/rules:maven_bom.bzl, isBuildPrelude=false}, KeyForWorkspace{label=@@bazel_features//:features.bzl, isBuildPrelude=false}, CONTAINING_PACKAGE_LOOKUP:@@bazel_features//, PACKAGE_LOOKUP:@@bazel_features//, REPOSITORY_DIRECTORY:@@bazel_features]
```

So rules_java isn't at fault here (sorry about the false alarm). Instead, https://github.com/bazel-contrib/rules_jvm_external/commit/3df00a601b8a2349341c3db93e2e398f5f78e890 introduced a dependency of rules_jvm_external on bazel_features, but https://github.com/JetBrains/hirschgarten/blob/bazel-steward/rules_jvm_external/6.4/WORKSPACE.bzlmod doesn't properly instantiate the WORKSPACE dependency macro of rules_jvm_external, which is a transitive dep of rules_sonatype but not listed in its deps section at https://github.com/JetBrains/hirschgarten/tree/main/rules_sonatype.

**Comment by gergelyfabian** [comment]
I don't know whether it changes anything but I can reproduce this issue without using bzlmod.

**Comment by agluszak** [comment]
@gergelyfabian and without using rules_sonatype?

**Comment by gergelyfabian** [comment]
According to my knowledge no sonatype in this project.

**Comment by gergelyfabian** [comment]
Reproduction:

https://github.com/gergelyfabian/bazel-scala-example/tree/rules_jvm_external_6.4

**Comment by hvadehra** [comment]
Closing this as rules_java does not seem to be at fault here.
