### ISSUE TITLE
Release: rules_java 7.12.1: deploy jar not provided for tests

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/rules_java#230]
## The project:
BUILD.bazel:
```py
load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "test",
    srcs = ["Test.java"],
    test_class = "Test",
    deps = [],
)
```

MODULE.bazel

```py
bazel_dep(name = "rules_java", version = "7.12.1")
```

Test.java
```java
public class Test {
    public static void main(String[] args) {

    }
}
```

## Scenario
run  `bazel build :test`

## Expected result:
`test_deploy.jar` is built (doc: https://bazel.build/reference/be/java#java_test_implicit_outputs)

## Actual result:
only `test.jar` is built

## References
https://github.com/bazelbuild/intellij/issues/6895

**Comment by mai93** [comment]
@tpasternak are we still passing `--experimental_java_test_auto_create_deploy_jar --output_groups=+_hidden_top_level_INTERNAL_` from plugin side, I see we had https://github.com/bazelbuild/intellij/commit/a61a2561a5733a7e441863b681fccd431b1ff3df to fix fast test for Bazel 7.

@hvadehra is there something else we should add?

**Comment by tpasternak** [comment]
Ok, I didn't know about the flag. We do pass it and it doesn't work

**Comment by tpasternak** [comment]
oh, wait, there is this thing https://github.com/bazelbuild/rules_java/commit/071069d0f20b1e39e11de5779947af366ac828c1

**Comment by tpasternak** [comment]
okay, fixed in 8.1.0

**Comment by hvadehra** [comment]
Sorry for the breakage, this actually happened in Bazel in https://github.com/bazelbuild/bazel/commit/364cc117df092d5ecc5a70da36c79432e365bd21

fwiw, I'm planning to backport the fix to rules_java 7.x as well.

**Comment by hvadehra** [comment]
FYI rules_java 7.12.2 with the fix https://github.com/bazelbuild/rules_java/commit/071069d0f20b1e39e11de5779947af366ac828c1 has been released and published to the BCR.

**Comment by tpasternak** [comment]
Thank you @hvadehra
