### ISSUE TITLE
bazelbuild/example/java-tutorial fails with rules_java version 8 and later

### ISSUE THREAD

**Issue by oleksii-danchuk** [bazelbuild/rules_java#237]
Bazel 7.4.0

bazelbuild/examples/java-tutorial
https://github.com/bazelbuild/examples/tree/main/java-tutorial

rules_java version 7.12.2 output:

❯ bazelisk query //...
//libs/java/java-tutorial:ProjectRunner
//libs/java/java-tutorial:ProjectRunner_deployjars_internal_rule
//libs/java/java-tutorial/src/main/java/com/example/cmdline:runner
//libs/java/java-tutorial/src/main/java/com/example/cmdline:runner_deployjars_internal_rule

rules_java version 8.0.0 and later output:

❯ bazelisk query //...
ERROR: Traceback (most recent call last):
        File "/home/username/.cache/bazel/_bazel_username/63b7ac9b1aa54a8af9b031bafe9119e9/external/rules_java~/java/common/rules/android_lint.bzl", line 142, column 31, in <toplevel>
                android_lint_subrule = subrule(
Error in subrule: file '@@rules_java~//java/common/rules:android_lint.bzl' cannot use private API
ERROR: error loading package under directory '': error loading package 'libs/java/java-tutorial/src/main/java/com/example/cmdline': at /home/username/.cache/bazel/_bazel_username/63b7ac9b1aa54a8af9b031bafe9119e9/external/rules_java~/java/defs.bzl:19:6: at
 /home/username/.cache/bazel/_bazel_username/63b7ac9b1aa54a8af9b031bafe9119e9/external/rules_java~/java/java_plugin.bzl:16:6: at /home/username/.cache/bazel/_bazel_username/63b7ac9b1aa54a8af9b031bafe9119e9/external/rules_java~/java/bazel/rules/bazel_java_
plugin.bzl:21:6: initialization of module 'java/common/rules/android_lint.bzl' failed

Could you please help to understand if there are some additional changes needed to use rules_java 8 and above?

**Comment by hvadehra** [comment]
See https://github.com/bazelbuild/rules_java/issues/233#issuecomment-2440998097

**Comment by hvadehra** [comment]
Update, rules_java 8.3.0 is available that does not suffer from this problem.

**Comment by oleksii-danchuk** [comment]
It works with 8.3.0, thanks!
