### ISSUE TITLE
Release: rules_java X.Y.Z

### ISSUE THREAD

**Issue by RosyCheek** [bazelbuild/rules_java#240]
I tried to build a buildfarm on ARM using bazel, but it failed. The same project configuration is successful on the x86. It seems to have something to do with the rules_java , but I don't know why.

The following error information is displayed:
ERROR: /app-buildfarm/.cache/e39f79732b8e64d60a97aef9f772a647/external/rules_java~5.5.1~toolchains~remote_java_tools/BUILD:372:11: error loading package '@rules_java~5.5.1~toolchains~remote_java_tools//java_tools/zlib': Unable to find package for @[unknown repo 'rules_license' requested from @rules_java~5.5.1~toolchains~remote_java_tools]//rules:license.bzl: The repository '@[unknown repo 'rules_license' requested from @rules_java~5.5.1~toolchains~remote_java_tools]' could not be resolved: No repository visible as '@rules_license' from repository '@rules_java~5.5.1~toolchains~remote_java_tools'. and referenced by '@rules_java~5.5.1~toolchains~remote_java_tools//:singlejar_cc_bin_main'

**Comment by iancha1992** [comment]
@hvadehra

**Comment by hvadehra** [comment]
Your rules_java version is really old at this point. Assuming you're using an old Bazel version as well, I think adding a dependency on rules_license to your WORKSPACE should fix things. https://github.com/bazelbuild/rules_license/releases/tag/0.0.4 is probably the one you want.
