### ISSUE TITLE
Action external/bazel_tools/tools/jdk/platformclasspath.jar fails with Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.

### ISSUE THREAD

**Issue by guw** [bazelbuild/rules_java#25]
Bazel 1.2.0

Goal: Compile and run Java source generator with `java_binary` during Bazel build with specific local Java 8 (ignoring whatever the environment says).

```
$ cat .bazelrc
build --javacopt="-source 8 -target 8"

build --define=ABSOLUTE_JAVABASE=/Library/Java/JavaVirtualMachines/my-openjdk1.8.0_212.jdk/Contents/Home
``` 

No further options defined in `.bazelrc`.

Here is the full output:
```
$ bazel build --verbose_failures --sandbox_debug //mypackage:mygenerator
INFO: Analyzed target //mypackage:mygenerator (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_username/d938ca62e478c52e9a414b5dc35f7a20/external/bazel_tools/tools/jdk/BUILD:309:1: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_username/d938ca62e478c52e9a414b5dc35f7a20/sandbox/darwin-sandbox/222/execroot/core && \
  exec env - \
    TMPDIR=/var/folders/9h/7v_bq0c55b19253s60bv5ym160zd9f/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_username/d938ca62e478c52e9a414b5dc35f7a20/sandbox/darwin-sandbox/222/sandbox.sb /var/tmp/_bazel_username/install/3c8c3e061eca79d4c8e8c05bb2875b69/process-wrapper '--timeout=0' '--kill_delay=15' /Library/Java/JavaVirtualMachines/my-openjdk1.8.0_212.jdk/Contents/Home/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/darwin-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:/Library/Java/JavaVirtualMachines/my-openjdk1.8.0_212.jdk/Contents/Home/lib/tools.jar DumpPlatformClassPath bazel-out/darwin-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/local_jdk)
Exception in thread "main" java.lang.AssertionError:
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.
Please file a bug: https://github.com/bazelbuild/bazel/issues
	at DumpPlatformClassPath.writeEntries(DumpPlatformClassPath.java:136)
	at DumpPlatformClassPath.writeClassPathJars(DumpPlatformClassPath.java:174)
	at DumpPlatformClassPath.dumpJDK8BootClassPath(DumpPlatformClassPath.java:77)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:65)
Target //mypackage:mygenerator failed to build
ERROR: /private/var/tmp/_bazel_username/d938ca62e478c52e9a414b5dc35f7a20/external/a_repo/.../BUILD:33:1 Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_username/d938ca62e478c52e9a414b5dc35f7a20/sandbox/darwin-sandbox/222/execroot/core && \
  exec env - \
    TMPDIR=/var/folders/9h/7v_bq0c55b19253s60bv5ym160zd9f/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_username/d938ca62e478c52e9a414b5dc35f7a20/sandbox/darwin-sandbox/222/sandbox.sb /var/tmp/_bazel_username/install/3c8c3e061eca79d4c8e8c05bb2875b69/process-wrapper '--timeout=0' '--kill_delay=15' /Library/Java/JavaVirtualMachines/my-openjdk1.8.0_212.jdk/Contents/Home/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/darwin-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:/Library/Java/JavaVirtualMachines/my-openjdk1.8.0_212.jdk/Contents/Home/lib/tools.jar DumpPlatformClassPath bazel-out/darwin-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/local_jdk)
INFO: Elapsed time: 0.460s, Critical Path: 0.23s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Note, the default Java on the machine is a different one, though. That should not be used for compilation.
```
$ java --version
openjdk 11.0.4 2019-07-16 LTS
OpenJDK Runtime Environment Zulu11.33+15-NV (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.33+15-NV (build 11.0.4+11-LTS, mixed mode)
```

**Comment by guw** [comment]
Adding the following to my `.bazelrc` fixed it:

```
build --define=ABSOLUTE_JAVABASE=....
build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
build --javabase=@bazel_tools//tools/jdk:absolute_javabase
build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
```

**Comment by yingshaoxo** [comment]
This helps too: `sudo apt install default-jdk`

**Comment by forestliurui** [comment]
@guw  Sorry, I am quite new to Bazel. I am trying to build a simple "Hello World" java example with Bazel. But   I got the the following error which looks quite similar to yours.
`$ bazel build  //src:HelloWorld --verbose_failures --sandbox_debug
INFO: Analyzed target //src:HelloWorld (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /private/var/.cache/bazel/_bazel_name/2f324277bc4aee23248b20c70a7448e3/external/bazel_tools/tools/jdk/BUILD:319:1: 
Action external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class failed (Exit 1) process-wrapper failed: error executing command
  (cd /private/var/.cache/bazel/_bazel_name/2f324277bc4aee23248b20c70a7448e3/sandbox/processwrapper-sandbox/8/execroot/__main__ && \
  exec env - \
    TMPDIR=/tmp \
    /private/var/.cache/bazel/_bazel_name/install/863382820ae9540178f3de18543a9280/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' 
    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.ppc64le/bin/javac -source 8 -target 8 -Xlint:-options 
    -cp /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-2.b14.el7.ppc64le/lib/tools.jar 
    -d bazel-out/ppc-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes 
    external/bazel_tools/tools/jdk/DumpPlatformClassPath.java)
/private/var/.cache/bazel/_bazel_name/install/863382820ae9540178f3de18543a9280/_embedded_binaries/process-wrapper: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /private/var/.cache/bazel/_bazel_name/install/863382820ae9540178f3de18543a9280/_embedded_binaries/process-wrapper)
Target //src:HelloWorld failed to build
INFO: Elapsed time: 0.095s, Critical Path: 0.01s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
`

My Bazel version is as follows:
`
$ bazel --version
bazel 1.1.0- (@non-git)
`
 
My Java version is as follows
`$ java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
`
Just wondering if you have any insight of how to fix it. Really appreciate any help.

**Comment by hundanLi** [comment]
> Adding the following to my `.bazelrc` fixed it:
> 
> ```
> build --define=ABSOLUTE_JAVABASE=....
> build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase
> build --javabase=@bazel_tools//tools/jdk:absolute_javabase
> build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
> build --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8
> ```

It works well for me.
