### ISSUE TITLE
Support arbitrary package prefix

### ISSUE THREAD

**Issue by fzakaria** [bazelbuild/rules_java#251]
https://github.com/bazelbuild/rules_java/blob/b3a0580e0a9a6b8b28b611c7dd6164c06b279539/java/common/rules/impl/java_helper.bzl#L127

Currently the code only supports com, org or net.
Critically for me it leaves out _io_ but it would great to support any prefix start.

I think the following would work:
```
if "src" == segment or (is_src and (segment in ["java", "javatests"])):
    next = segments[i + 1]
    if "src" == segment:
        check_mvn_idx = i
    # record next segment as root 
    # may be overwritten by check_mvn code below
    root_idx = i
    break
```

**Comment by hvadehra** [comment]
https://github.com/bazelbuild/bazel/issues/6353 is the canonical FR for this. Closing this, please continue discussion there.
