### ISSUE TITLE
Building simple java proto fails with ERROR: ERROR: error loading package '': cannot load '@rules_java//java:repositories.bzl': no such file  

### ISSUE THREAD

**Issue by maks-a** [bazelbuild/rules_java#43]
I am creating a simple hello world project that uses protobuf and it fails on the first stage of building java protos.

Added to [WORKSPACE](https://gitlab.com/mvfwd/hello-bazel/-/blob/dev-java/WORKSPACE#L66) as described [here](https://github.com/bazelbuild/rules_java/releases):
```
http_archive(
    name = "rules_java",
    url = "https://github.com/bazelbuild/rules_java/releases/download/4.0.0/rules_java-4.0.0.tar.gz",
    sha256 = "34b41ec683e67253043ab1a3d1e8b7c61e4e8edefbcad485381328c934d072fe",
)
load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")
rules_java_dependencies()
rules_java_toolchains()
```
Here is the failure:
```
$ bazel build //proto::person_java_proto
ERROR: error loading package '': cannot load '@rules_java//java:repositories.bzl': no such file
INFO: Elapsed time: 0.219s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Can anybody give me a hand please?

**Comment by comius** [comment]
In your particular example, another version of rules_java gets loaded by protobuf_deps (you can find calls stack by running `bazel query '//external:all' --output=build`).

Bazel will load repo by first occurrence of its http_archive.

Removing rules_java from your WORKSPACE works.

We're working towards a better dependency resolution, see bzlmod docs https://docs.google.com/document/d/1moQfNcEIttsk6vYanNKIy3ZuK53hQUFq1b1r0rmsYVg/edit

**Comment by maks-a** [comment]
This solution works, thank you, @comius !
