### ISSUE TITLE
Adding `@bazel_tools//tools/java/runfiles` to `rules_java`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/rules_java#46]
Would you welcome a PR that adds the Bazel Java runfiles library, which is available at `@bazel_tools//tools/java/runfiles`, to `rules_java`? According to the [Starlark "Deploying rules"](https://docs.bazel.build/versions/main/skylark/deploying.html) guide, it should be available at `@rules_java//java/runfiles`.

I am specifically asking this because I found [an issue](https://github.com/bazelbuild/bazel/issues/14336) with the version of the runfiles libraries currently bundled with Bazel and am wondering about how future improvements to these libraries could be published so that users on older Bazel versions could still use them. Especially now that modules exist, `rules_java` is bound to get far more commonly used and would be a more natural place for modules to get the runfiles library from than `@bazel_tools`.

**Comment by comius** [comment]
It makes sense to put @bazel_tools//tools/java/runfiles here, because it's only needed by Java projects.

We'd actually want @bazel_tools removed one day, so it's a welcome change. The tricky part is probably how to add it here and then remove it from @bazel_tools. Not to have duplicated code.

**Comment by hvadehra** [comment]
@fmeum I suppose this is now done?
