### ISSUE TITLE
5.0 release lacks workspace setup (SHA): https://github.com/bazelbuild/rules_java/releases

### ISSUE THREAD

**Issue by lukepopp** [bazelbuild/rules_java#52]
Just staring with Bazel and can't see the SHA etc as part of the release

**Comment by lukepopp** [comment]
Thanks @mmellin , I also found under Bazel 5 I didn't need to supply the http_archive - it just worked.  I haven't verified the version of java_rules pulled in though.

**Comment by tetromino** [comment]
Note that the release tagged as 5.0.0 seems to be missing
* the correct version number in //java:defs.bzl
* a release tarball (which the maintainers would normally generate via `bazel build //distro:rules_java-5.0.0` and mirror the tarball on mirror.bazel.build)

**Comment by comius** [comment]
> Note that the release tagged as 5.0.0 seems to be missing
> 
> * the correct version number in //java:defs.bzl
> * a release tarball (which the maintainers would normally generate via `bazel build //distro:rules_java-5.0.0` and mirror the tarball on mirror.bazel.build)

You're right. The release was botched. I followed the proper procedure now.

Please use the release instructions.
