### ISSUE TITLE
Push a new release containing latest JDK versions

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/rules_java#66]
Could we push a new release of rules_java that contains https://github.com/bazelbuild/rules_java/commit/36a7611fd6ac6bf6970e1c4dff57a6e43e91c47e? Then we could push the new version to BCR, which fixes a bug in Bazel when building with Bzlmod enabled (https://github.com/bazelbuild/bazel/issues/16109).

We should probably first decide what the next version number should be, since the MODULE.bazel file needs to be updated too.

**Comment by comius** [comment]
I'll do a release. How does `5.1.0` sound? (javac jars have been removed, so I think it calls for a minor version increase)

**Comment by Wyverald** [comment]
5.1.0 sounds good to me. Ideally https://github.com/bazelbuild/rules_java/pull/67 should be included as well. Thanks!

**Comment by comius** [comment]
Done.
