### ISSUE TITLE
Using default_java_toolchain, etc from //toolchains as opposed to @bazel_tools doesn't work

### ISSUE THREAD

**Issue by gmishkin** [bazelbuild/rules_java#70]
get errors like 

```
ERROR: /Users/geoff/code/mms/server/BUILD.bazel:592:23: no such package 'toolchains': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/geoff/code/mms/toolchains and referenced by '//server:java_toolchain_config'
ERROR: /Users/geoff/code/mms/server/BUILD.bazel:592:23: no such package 'toolchains': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/geoff/code/mms/toolchains and referenced by '//server:java_toolchain_config'
ERROR: /Users/geoff/code/mms/server/BUILD.bazel:592:23: no such package 'toolchains': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/geoff/code/mms/toolchains and referenced by '//server:java_toolchain_config'
ERROR: /Users/geoff/code/mms/server/BUILD.bazel:592:23: no such package 'toolchains': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/geoff/code/mms/toolchains and referenced by '//server:java_toolchain_config'
```

I assume it's because all the labels in default_java_toolchain.bzl like "//toolchains:singlejar" need to be wrapped in `Label()` or something so that they're relative to @rules_java?

**Comment by gmishkin** [comment]
Just as a heads up, this is an issue now when using default_java_toolchain from `@bazel_tools` on recent versions of rules_java, because rules_java now points to a version of remote_java_tools that no longer provides a `java_compiler_jar`, but bazel_tools' default_java_toolchain tries to patch the java module with `@remote_java_tools//:java_compiler_jar` which no longer exists.

**Comment by Wyverald** [comment]
Could we do a rules_java release for this?

**Comment by SimonVleugels** [comment]
@comius, When can we expect a new rules_java release? This is a blocking issue for us and we are trying to avoid using the master branch.

**Comment by Wyverald** [comment]
To close the loop: there is a new release now https://registry.bazel.build/modules/rules_java
