### ISSUE TITLE
java_proto_library build broken by No matching toolchains found for types @bazel_tools//tools/python:toolchain_type.

### ISSUE THREAD

**Issue by xushaoxiao** [bazelbuild/rules_java#93]
LCNC02GG727MD6R:allinone-via-bazelmod shaoxixu$ bazel build --enable_bzlmod ...
ERROR: /private/var/tmp/_bazel_shaoxixu/4d55580d1e210b29889ae47b4f95eda7/external/bazel_tools/tools/jdk/BUILD:393:10: While resolving toolchains for target @bazel_tools//tools/jdk:proguard_whitelister: No matching toolchains found for types @bazel_tools//tools/python:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@bazel_tools//tools/python:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
ERROR: Analysis of target '//grpc_ecosystem/protobuf/support:pagination_java_proto' failed; build aborted: 
INFO: Elapsed time: 11.887s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (117 packages loaded, 10899 targets configured)
    currently loading: @protobuf~21.7//java/core
    Fetching https://bcr.bazel.build/bazel_registry.json

**Comment by xushaoxiao** [comment]
![image](https://user-images.githubusercontent.com/83151234/225859061-302e2746-5fd8-4cad-bc69-43a90e73093c.png)

**Comment by hvadehra** [comment]
Hi @xushaoxiao What version of bazel and rules_java are you using?
